#!/usr/bin/env bash


# cd to application folder
cd "$( dirname "${BASH_SOURCE[0]}" )/.."

case "$1" in
  'export')
    node ./scripts/db-export.js "$2"
    ;;
  'reset')
    echo -n "Really reset the database? [y/N] "
    read answer
    if [ "$answer" != "${answer#[Yy]}" ] ;then
      # drop and recreate all model tables
      npx sequelize db:migrate:undo
      npx sequelize db:migrate

      # remove all data and populate with seed data
      npx sequelize db:seed:undo:all
      npx sequelize db:seed:all
    fi
    ;;
  *)
    echo 'Usage:'
    echo -e "\t$0 export [model] \tExports all (or model only) data from the database"
    echo -e "\t$0 reset          \tRecreate all tables and populate with seeders data"
    exit 1
    ;;
esac
