#!/usr/bin/env bash

case "$1" in
  '')
    # connect to virtual machine

    # run `vagrant up` if it's not up already
    vagrant status | grep 'default\s*running' -q || vagrant up
    vagrant ssh

    echo ''
    echo -e 'Remember to run "\e[33mvagrant suspend\e[39m" when done working to save laptop battery'
    ;;
  'update')
    # update virtual machine and run ansible
    vagrant up --provision
    ;;
  *)
    echo 'Usage:'
    echo -e "\t$0        \tConnect to virtual machine"
    echo -e "\t$0 update \tUpdate and run ansible on virtual machine"
    exit 1
    ;;
esac
