#!/usr/bin/env bash

# run `vagrant up` if it's not up already
vagrant status | grep 'default\s*running' -q || vagrant up
vagrant ssh

echo ''
echo -e "Remember to run '\e[33mvagrant suspend\e[39m' when done working"
