#!/usr/bin/env bash

# this ssh key path is relative to project root
export GIT_SSH_COMMAND='ssh -i credentials/ssh/id_csc648'
export prod_user='csc648'
export prod_ip='34.82.221.18'

# the rest of the paths are relative to the application folder
cd "$( dirname "${BASH_SOURCE[0]}" )/.."

case "$1" in
  'ansible')
    ansible-playbook -i provision/webserver.ini provision/ansible.yml
    ;;
  'code')
    if git remote | grep 'prod' -q; then
      echo 'Pushing branch master'
      git push prod master
    else
      # add new remote and push master branch to it
      echo 'Creating git remote "prod"'
      git remote add prod ssh://${prod_user}@${prod_ip}/home/${prod_user}/csc648-fall2019-Team12.git
      echo 'Pushing branch master'
      git push prod +master:refs/heads/master
    fi
    ;;
  'ssh')
    ssh -i ../credentials/ssh/id_csc648 ${prod_user}@${prod_ip}
    ;;
  'update')
    ssh -i ../credentials/ssh/id_csc648 ${prod_user}@${prod_ip} 'sudo bash -s' < provision/bootstrap.sh
    ;;
  *)
    echo 'Usage:'
    echo -e "\t$0 ansible \tRun ansible on production"
    echo -e "\t$0 code    \tPush master branch to production"
    echo -e "\t$0 ssh     \tOpen SSH to production"
    echo -e "\t$0 update  \tUpdate production server"
    exit 1
    ;;
esac
