---
- name: Create node_modules folder
  file:
    path: /home/vagrant/node_modules
    state: directory
    owner: vagrant
    group: vagrant

- name: Create node_modules symlink
  file:
    src: /home/vagrant/node_modules
    dest: /vagrant/node_modules
    state: link
