---
- hosts: all
  become: yes
  vars:
    nodejs_version: "10"
    ubuntu_release: "bionic"
    webserver_port: "1648"

  handlers:
    - name: Restart nginx
      service:
        name: nginx
        state: restarted

  tasks:
    - name: Install the gpg key for nodejs LTS
      apt_key:
        url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"

    - name: Install nodejs LTS repos
      apt_repository:
        repo: "deb https://deb.nodesource.com/node_{{ nodejs_version }}.x {{ ubuntu_release }} main"

    - name: Install packages
      apt:
        name: "{{ packages }}"
      vars:
        packages:
          - nodejs
          - mysql-server
          - nginx

    - name: Remove default nginx conf
      file:
        state: absent
        path: /etc/nginx/sites-enabled/default

    - name: Add custom nginx conf
      template:
        src: nginx.conf.template
        dest: /etc/nginx/sites-enabled/webserver.conf
      notify: Restart nginx

- hosts: default
  become: yes
  tasks:
    - name: Create node_modules folder
      file:
        path: /home/vagrant/node_modules
        state: directory
        owner: vagrant
        group: vagrant

    - name: Create node_modules symlink
      file:
        src: /home/vagrant/node_modules
        dest: /vagrant/node_modules
        state: link
