---
- hosts: all
  become: yes
  vars:
    nodejs_version: "10"
    ubuntu_release: "bionic"
    webserver_port: "1648"

  handlers:
    - name: Restart nginx
      service:
        name: nginx
        state: restarted

  tasks:
    - name: Install the gpg key for nodejs LTS
      apt_key:
        url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"

    - name: Install nodejs LTS repos
      apt_repository:
        repo: "deb https://deb.nodesource.com/node_{{ nodejs_version }}.x {{ ubuntu_release }} main"

    - name: Install packages
      apt:
        name: "{{ packages }}"
      vars:
        packages:
          - git
          - nodejs
          - mysql-server
          - nginx
          - htop

    - name: Remove default nginx conf
      file:
        state: absent
        path: /etc/nginx/sites-enabled/default

    - name: Add custom nginx conf
      template:
        src: nginx.conf.template
        dest: /etc/nginx/sites-enabled/webserver.conf
      notify: Restart nginx

- hosts: webserver
  become: yes
  vars:
    remote_repo_path: "/home/csc648/csc648-fall2019-Team12"

  tasks:
    - name: Create git folder
      command: "git init --bare {{ remote_repo_path }}.git"
      args:
        creates: "{{ remote_repo_path }}.git/HEAD"
      become_user: csc648

    - name: Copy post-receive hook
      template:
        src: post-receive.template
        dest: "{{ remote_repo_path }}.git/hooks/post-receive"
        owner: csc648
        group: csc648
        mode: u=rwx,g=rx,o=rx

    - name: Create git working directory
      file:
        path: "{{ remote_repo_path }}"
        state: directory
        owner: csc648
        group: csc648

    - name: Install Node.js pm2
      npm:
        name: pm2
        global: yes

- hosts: default
  become: yes
  tasks:
    - name: Create node_modules folder
      file:
        path: /home/vagrant/node_modules
        state: directory
        owner: vagrant
        group: vagrant

    - name: Create node_modules symlink
      file:
        src: /home/vagrant/node_modules
        dest: /vagrant/node_modules
        state: link
